### ISSUE TITLE
Remove Make

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber-react#10]
** What's the problem you've observed? 🤔 **

Make is used for some orchetration, and you need to run `make` locally before you can run the tests.

Not everyone has Make (e.g. Windows) or knows how to use it, and might be a bit surprising for a frontend developer approaching this project to contribute.

** Do you have a proposal for making it better? 🦄 **

What we're going with Make is pretty minor, this could be moved into the npm `prepare` script meaning it's handled as part of `npm install`.

**Comment by aslakhellesoy** [comment]
Yeah it’s just a bit of file concatenation to do codegen. Can be done in a js file we call from npm.
