### ISSUE TITLE
Scenario Outline Styling

### ISSUE THREAD

**Issue by ludeknovy** [cucumber/cucumber-react#130]
### 🤔 What's the problem you're trying to solve?

To make the HTML report with Scenario Outlines easier to read.

### ✨ What's your proposed solution?

* "Scenario Outline" and "Examples" both are H2 tags. I suggest using H3 for "Examples".
* Align "Examples" with steps (move it slightly to the right)

### ⛏ Have you considered any alternatives or workarounds?

No

### 📚 Any additional context?

If agreed I am willing to contribute.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by ludeknovy** [comment]
Before vs after screenshots.

![before](https://user-images.githubusercontent.com/13610612/162408610-17821411-44bb-45f0-a98e-c6d3ff5d39eb.png)
![after](https://user-images.githubusercontent.com/13610612/162408619-04f2d656-3c54-4b31-997c-9b92a17c73e8.png)

**Comment by davidjgoss** [comment]
Yeah this seems better to me.

@aslakhellesoy @mattwynne any thoughts?
