### ISSUE TITLE
Missing @typescript-eslint/parser dependency

### ISSUE THREAD

**Issue by ludeknovy** [cucumber/cucumber-react#133]
### 🤔 What's the problem you've observed?

When running `npm install` and followed by `npm run eslint`, the later command fails as `@typescript-eslint/parser` is not installed.

```
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module '@typescript-eslint/parser'
```

### ✨ Do you have a proposal for making it better?

Include `@typescript-eslint/parser` in dev dependencies.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by davidjgoss** [comment]
Thanks for raising @ludeknovy, I've added the fix to https://github.com/cucumber/cucumber-react/pull/131
