### ISSUE TITLE
TS Compilation error with scss running tests

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-react#6]
After I migrated the code from `cucumber/common` I am no longer able to run tests:

```
npm test

TSError: ⨯ Unable to compile TypeScript:
src/components/app/ExecutionSummary.tsx:14:20 - error TS2307: Cannot find module './ExecutionSummary.module.scss' or its corresponding type declarations.

14 import styles from './ExecutionSummary.module.scss'
```

Any idea what I broke and how to fix this @davidjgoss?

**Comment by davidjgoss** [comment]
Fixed the SCSS issue by adding some missing tsconfig.

Next up is an acceptance test failing on a relative import of the gherkin test data https://github.com/cucumber/common/tree/main/gherkin/testdata. This isn't currently published in any package. We could potentially include it in the `@cucumber/gherkin-utils` package? Meantime I'll add it to the repo as a temporary measure.
