### ISSUE TITLE
Allow text attachment to be collapsible

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-react#78]
Allow scenario logs to be collapsible:
![Screenshot from 2021-02-03 17-48-51](https://user-images.githubusercontent.com/17047317/106772038-47032900-6648-11eb-83c7-2191b16c04fd.png)
Large text data will make the report harder to follow

**Comment by mattwynne** [comment]
That's great that you have a solution!

IMO it would be preferable to default to collapsing attachments rather than having an option.

Do you want to make a PR @Johnlon and we can discuss it there?

**Comment by Johnlon** [comment]
I will

**Comment by Johnlon** [comment]
@mattwynne  Done https://github.com/cucumber/cucumber-react/pull/108

Leverages the "details" html tag so the appearance is determined by the browser.
Here's chrome ...
 
![image](https://user-images.githubusercontent.com/836248/159603370-21f138c1-760e-459e-bb45-c4e9d318cba6.png)

**Comment by mattwynne** [comment]
> if the attachment hasn't been given a filename then the title (aka "summary") is the word "text".

Does this also work for image attachments?

**Comment by davidjgoss** [comment]
Image attachments already have this.

**Comment by Johnlon** [comment]
Folk, what's the process / timeline  for getting this integrated?

**Comment by Johnlon** [comment]
Same done for Video Attachment inc missing tests

**Comment by Johnlon** [comment]
Change is merged but presumably this ticket will stay open until the build is available for consumption?

**Comment by aurelien-reeves** [comment]
I guess we can close it

Thanks again @Johnlon 💪

**Comment by Johnlon** [comment]
I would only close when the value is realised.

**Comment by aurelien-reeves** [comment]
It depends on how the organization typically works.
At cucumber, we usually close such tickets once related PR are merged and the fix is on main.
